coverage:
  status:
    project:
      default:
        target: auto  # Automatically set target coverage based on historical data
        threshold: 3% # Allowable coverage drop before raising a warning

comment:
  layout: "header, diff, flags, components"  # Specify the layout for the PR comment, showing component info

component_management:
  default_rules:  # Default rules applied to all components unless overridden
    statuses:
      - type: project # Default status type for components without specific status
        target: auto
        branches:
          - "!main"  # Apply rules to all branches except 'main'
  individual_components:
    - component_id: module_core
      name: core
      paths:
        - solidity/contracts/Mailbox.sol  # Path to the core component
    - component_id: module_hooks
      name: hooks
      paths:
        - solidity/contracts/hooks/**  # Path to hooks component, includes all subdirectories
    - component_id: module_isms
      name: isms
      paths:
        - solidity/contracts/isms/**  # Path to isms component, includes all subdirectories
    - component_id: module_token
      name: token
      paths:
        - solidity/contracts/token/**  # Path to token component, includes all subdirectories
    - component_id: module_middlewares
      name: middlewares
      paths:
        - solidity/contracts/middleware/**  # Path to middlewares component, includes all subdirectories
